# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dave/c-c++/fantasy-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dave/c-c++/fantasy-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/c-c++/fantasy-core/CMakeFiles /home/dave/c-c++/fantasy-core/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/c-c++/fantasy-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fantasy-core

# Build rule for target.
fantasy-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fantasy-core
.PHONY : fantasy-core

# fast build rule for target.
fantasy-core/fast:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/build
.PHONY : fantasy-core/fast

src/fantasIA-gtk.o: src/fantasIA-gtk.c.o
.PHONY : src/fantasIA-gtk.o

# target to build an object file
src/fantasIA-gtk.c.o:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasIA-gtk.c.o
.PHONY : src/fantasIA-gtk.c.o

src/fantasIA-gtk.i: src/fantasIA-gtk.c.i
.PHONY : src/fantasIA-gtk.i

# target to preprocess a source file
src/fantasIA-gtk.c.i:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasIA-gtk.c.i
.PHONY : src/fantasIA-gtk.c.i

src/fantasIA-gtk.s: src/fantasIA-gtk.c.s
.PHONY : src/fantasIA-gtk.s

# target to generate assembly for a file
src/fantasIA-gtk.c.s:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasIA-gtk.c.s
.PHONY : src/fantasIA-gtk.c.s

src/fantasIA.o: src/fantasIA.c.o
.PHONY : src/fantasIA.o

# target to build an object file
src/fantasIA.c.o:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasIA.c.o
.PHONY : src/fantasIA.c.o

src/fantasIA.i: src/fantasIA.c.i
.PHONY : src/fantasIA.i

# target to preprocess a source file
src/fantasIA.c.i:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasIA.c.i
.PHONY : src/fantasIA.c.i

src/fantasIA.s: src/fantasIA.c.s
.PHONY : src/fantasIA.s

# target to generate assembly for a file
src/fantasIA.c.s:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasIA.c.s
.PHONY : src/fantasIA.c.s

src/fantasy-gtk.o: src/fantasy-gtk.c.o
.PHONY : src/fantasy-gtk.o

# target to build an object file
src/fantasy-gtk.c.o:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-gtk.c.o
.PHONY : src/fantasy-gtk.c.o

src/fantasy-gtk.i: src/fantasy-gtk.c.i
.PHONY : src/fantasy-gtk.i

# target to preprocess a source file
src/fantasy-gtk.c.i:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-gtk.c.i
.PHONY : src/fantasy-gtk.c.i

src/fantasy-gtk.s: src/fantasy-gtk.c.s
.PHONY : src/fantasy-gtk.s

# target to generate assembly for a file
src/fantasy-gtk.c.s:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-gtk.c.s
.PHONY : src/fantasy-gtk.c.s

src/fantasy-lib.o: src/fantasy-lib.c.o
.PHONY : src/fantasy-lib.o

# target to build an object file
src/fantasy-lib.c.o:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-lib.c.o
.PHONY : src/fantasy-lib.c.o

src/fantasy-lib.i: src/fantasy-lib.c.i
.PHONY : src/fantasy-lib.i

# target to preprocess a source file
src/fantasy-lib.c.i:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-lib.c.i
.PHONY : src/fantasy-lib.c.i

src/fantasy-lib.s: src/fantasy-lib.c.s
.PHONY : src/fantasy-lib.s

# target to generate assembly for a file
src/fantasy-lib.c.s:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-lib.c.s
.PHONY : src/fantasy-lib.c.s

src/fantasy-loadsave.o: src/fantasy-loadsave.c.o
.PHONY : src/fantasy-loadsave.o

# target to build an object file
src/fantasy-loadsave.c.o:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-loadsave.c.o
.PHONY : src/fantasy-loadsave.c.o

src/fantasy-loadsave.i: src/fantasy-loadsave.c.i
.PHONY : src/fantasy-loadsave.i

# target to preprocess a source file
src/fantasy-loadsave.c.i:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-loadsave.c.i
.PHONY : src/fantasy-loadsave.c.i

src/fantasy-loadsave.s: src/fantasy-loadsave.c.s
.PHONY : src/fantasy-loadsave.s

# target to generate assembly for a file
src/fantasy-loadsave.c.s:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-loadsave.c.s
.PHONY : src/fantasy-loadsave.c.s

src/fantasy-main.o: src/fantasy-main.c.o
.PHONY : src/fantasy-main.o

# target to build an object file
src/fantasy-main.c.o:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-main.c.o
.PHONY : src/fantasy-main.c.o

src/fantasy-main.i: src/fantasy-main.c.i
.PHONY : src/fantasy-main.i

# target to preprocess a source file
src/fantasy-main.c.i:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-main.c.i
.PHONY : src/fantasy-main.c.i

src/fantasy-main.s: src/fantasy-main.c.s
.PHONY : src/fantasy-main.s

# target to generate assembly for a file
src/fantasy-main.c.s:
	$(MAKE) -f CMakeFiles/fantasy-core.dir/build.make CMakeFiles/fantasy-core.dir/src/fantasy-main.c.s
.PHONY : src/fantasy-main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fantasy-core"
	@echo "... rebuild_cache"
	@echo "... src/fantasIA-gtk.o"
	@echo "... src/fantasIA-gtk.i"
	@echo "... src/fantasIA-gtk.s"
	@echo "... src/fantasIA.o"
	@echo "... src/fantasIA.i"
	@echo "... src/fantasIA.s"
	@echo "... src/fantasy-gtk.o"
	@echo "... src/fantasy-gtk.i"
	@echo "... src/fantasy-gtk.s"
	@echo "... src/fantasy-lib.o"
	@echo "... src/fantasy-lib.i"
	@echo "... src/fantasy-lib.s"
	@echo "... src/fantasy-loadsave.o"
	@echo "... src/fantasy-loadsave.i"
	@echo "... src/fantasy-loadsave.s"
	@echo "... src/fantasy-main.o"
	@echo "... src/fantasy-main.i"
	@echo "... src/fantasy-main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

